from __future__ import annotations

TILE_SIZE = 16

MAP_TILE_WIDTH = 10
MAP_TILE_HEIGHT = 8
HUD_TILE_HEIGHT = 2

SCREEN_TILE_WIDTH = 10
SCREEN_TILE_HEIGHT = 10

SCREEN_WIDTH = SCREEN_TILE_WIDTH * TILE_SIZE
SCREEN_HEIGHT = SCREEN_TILE_HEIGHT * TILE_SIZE

MAP_PIXEL_WIDTH = MAP_TILE_WIDTH * TILE_SIZE
MAP_PIXEL_HEIGHT = MAP_TILE_HEIGHT * TILE_SIZE
HUD_PIXEL_HEIGHT = HUD_TILE_HEIGHT * TILE_SIZE
HUD_PIXEL_Y = MAP_PIXEL_HEIGHT

INTERNAL_WIDTH = SCREEN_WIDTH
INTERNAL_HEIGHT = SCREEN_HEIGHT
MAP_WIDTH_TILES = MAP_TILE_WIDTH
MAP_HEIGHT_TILES = MAP_TILE_HEIGHT
WINDOW_SCALE = 4
SCALE_FACTOR = WINDOW_SCALE
WINDOW_WIDTH = SCREEN_WIDTH * WINDOW_SCALE
WINDOW_HEIGHT = SCREEN_HEIGHT * WINDOW_SCALE

GRID_WIDTH = MAP_TILE_WIDTH
GRID_HEIGHT = MAP_TILE_HEIGHT

ENTITY_SIZE_PX = TILE_SIZE
PLAYER_SIZE_PX = TILE_SIZE
MONSTER_SIZE_PX = TILE_SIZE

PLAYER_SPEED_PX_PER_TICK = 1.0
MONSTER_SPEED_RATIO = 0.5
MONSTER_SPEED_PX_PER_TICK = PLAYER_SPEED_PX_PER_TICK * MONSTER_SPEED_RATIO

# Backward-compatible aliases for older imports. The unit is one environment
# tick, not a tile step.
PLAYER_SPEED_PX_PER_STEP = PLAYER_SPEED_PX_PER_TICK
MONSTER_SPEED_PX_PER_STEP = MONSTER_SPEED_PX_PER_TICK

PLAYER_HP_DEFAULT = 5
PLAYER_GOLD_DEFAULT = 0
PLAYER_KEYS_DEFAULT = 0

TARGET_FPS = 60

MONSTER_HIT_KNOCKBACK_PX = TILE_SIZE
MONSTER_STUN_TICKS = TARGET_FPS
PLAYER_ACTION_DURATION_TICKS = 6
SWORD_SWING_DURATION_TICKS = PLAYER_ACTION_DURATION_TICKS
SHIELD_RAISE_DURATION_TICKS = PLAYER_ACTION_DURATION_TICKS

MONSTER_DEFAULT_HP = 3
MONSTER_KILL_GOLD_REWARD = 2

ACTION_NOOP = 0
ACTION_UP = 1
ACTION_DOWN = 2
ACTION_LEFT = 3
ACTION_RIGHT = 4
ACTION_A = 5
ACTION_B = 6

ACTION_LABELS = {
    ACTION_NOOP: "WAIT",
    ACTION_UP: "UP",
    ACTION_DOWN: "DOWN",
    ACTION_LEFT: "LEFT",
    ACTION_RIGHT: "RIGHT",
    ACTION_A: "BUTTON_A",
    ACTION_B: "BUTTON_B",
}

DIRECTION_VECTORS = {
    "up": (0.0, -1.0),
    "down": (0.0, 1.0),
    "left": (-1.0, 0.0),
    "right": (1.0, 0.0),
}

MOVE_ACTION_TO_DIRECTION = {
    ACTION_UP: "up",
    ACTION_DOWN: "down",
    ACTION_LEFT: "left",
    ACTION_RIGHT: "right",
}

ITEM_NAME_TO_ID = {
    "empty": 0,
    "sword": 1,
    "shield": 2,
    "key": 3,
    "potion": 4,
}

COLOR_FRAME_BG = (72, 122, 248)
COLOR_MAP_BG = (72, 122, 248)
COLOR_MAP_GRID = (36, 82, 206)
COLOR_WALL = (219, 18, 82)
COLOR_PLAYER = (36, 198, 72)
COLOR_CHEST = (152, 82, 36)
COLOR_CHEST_OPEN = (40, 190, 74)
COLOR_NPC = (240, 154, 52)
COLOR_MONSTER_CHASER = (238, 126, 28)
COLOR_MONSTER_AMBUSHER = (255, 180, 48)
COLOR_MONSTER_PATROLLER = (200, 78, 16)
COLOR_TRAP = (112, 112, 126)
COLOR_BUTTON = (40, 190, 74)
COLOR_SWITCH = (255, 216, 80)
COLOR_GAP = (16, 22, 48)
COLOR_BRIDGE = (172, 104, 48)
COLOR_EXIT_NORMAL = (255, 244, 112)
COLOR_EXIT_LOCKED = (96, 48, 26)
COLOR_EXIT_CONDITIONAL = (255, 216, 80)
COLOR_HUD_BG = (255, 255, 255)
COLOR_HUD_PANEL = (238, 238, 236)
COLOR_HUD_ACCENT = (8, 8, 16)
COLOR_HUD_TEXT = (8, 8, 16)
COLOR_HUD_TEXT_DIM = (42, 45, 88)

MESSAGE_DEFAULT = "EXPLORE"
